In [1]:
import sys
import nltk
import sklearn
import pandas
import numpy

import pandas as pd
import numpy as np
df = pd.read_csv('Bug Reports Dataset.csv')
print (df.head(5))

    Bug ID              Product       Component Assignee       Status  \
0  1420563              Firefox         General   nobody          NEW   
1  1425665              Firefox           Theme   nobody          NEW   
2  1397909  Firefox for Android         General   nobody          NEW   
3  1449219              Firefox  Tabbed Browser   nobody  UNCONFIRMED   
4  1508122  Firefox for Android         General   nobody          NEW   

    Classification Priority            Opened  \
0  Client Software       P1  11/24/2017 23:02   
1  Client Software       P2   12/16/2017 4:45   
2  Client Software       P2    9/7/2017 14:06   
3  Client Software       P2    3/27/2018 8:45   
4  Client Software       P2   11/18/2018 0:09   

                                             Summary         Category  
0  "Authentication Required" hangs Firefox when C...      Performance  
1  print preview buttons not readable on windows ...              GUI  
2  This page causes Firefox to completely hang fo.

In [4]:
classes = df['Priority']
print(classes.value_counts())

P3    925
P2    539
P1    294
P5    225
P4    155
Name: Priority, dtype: int64


In [5]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
Y = encoder.fit_transform (classes)
print(classes[:8])
print(Y[:8])
summary = df['Summary']
print(summary[:10])

0    P1
1    P2
2    P2
3    P2
4    P2
5    P3
6    P3
7    P3
Name: Priority, dtype: object
[0 1 1 1 1 2 2 2]
0    "Authentication Required" hangs Firefox when C...
1    print preview buttons not readable on windows ...
2    This page causes Firefox to completely hang fo...
3    hang with encoded character in userinfo (https...
4    Crash in java.lang.IllegalArgumentException: a...
5    The One-Off search 2nd line buttons are not vi...
6    Statusbar text not visible in firefox 57 andro...
7    "Open a new tab" button is not visible when th...
8    Intersection of full-height tab separators and...
9    The browser window's UI is not entirely visibl...
Name: Summary, dtype: object


In [6]:
import re
processed = re.sub(r'[\d]', ' ',str(summary))
print(processed)

        "Authentication Required" hangs Firefox when C...
        print preview buttons not readable on windows ...
        This page causes Firefox to completely hang fo...
        hang with encoded character in userinfo (https...
        Crash in java.lang.IllegalArgumentException: a...
        The One-Off search  nd line buttons are not vi...
        Statusbar text not visible in firefox    andro...
        "Open a new tab" button is not visible when th...
        Intersection of full-height tab separators and...
        The browser window's UI is not entirely visibl...
        [Dark Theme] Placeholder text color differs be...
        Error when I click "Pocket" button: "Security ...
        about:networking shows domains visited in Priv...
        Hang when displaying Unsorted Bookmarks with  ...
        Moving place: bookmark for Bookmarks Menu caus...
        Firefox hangs trying to open broken site for t...
        Specific PDF  page takes   s to render (   % cpu)
        Firefo

In [7]:
processed = summary.str.replace(r'(\d)' , '')
processed = processed.str.replace(r'^\D?(\d{3})\D?\D?(\d{3})\D?(\d{4})$' , ' ')
processed = processed.str.replace(r'\s+' , ' ')
processed = processed.str.replace(r'[ \t]+$' , ' ')
processed = processed.str.replace(r'[&#();*]' , ' ')
processed = processed.str.replace(r'[,:]' , ' ')
processed = processed.str.replace(r'[.!?\\-]' , ' ')
processed = processed.str.replace(r'[//]' , ' ')
processed = processed.str.replace(r'[|]' , ' ')
processed = processed.str.replace(r'\'' , ' ')
processed = processed.str.lower()
processed = processed.str.replace(r'\s[a-z]\s' , ' ')
processed = processed.str.replace(r'\[[^\]]*\]',' ')
processed = processed.str.replace(r'\"',' ')
processed = processed.str.replace(r'\`',' ')
print(processed)

0        authentication required  hangs firefox when c...
1       print preview buttons not readable on windows ...
2       this page causes firefox to completely hang fo...
3       hang with encoded character in userinfo  https...
4       crash in java lang illegalargumentexception  a...
5       the one off search nd line buttons are not vis...
6       statusbar text not visible in firefox android ...
7        open new tab  button is not visible when the ...
8       intersection of full height tab separators and...
9       the browser window ui is not entirely visible ...
10        placeholder text color differs between addre...
11      error when click  pocket  button   security er...
12      about networking shows domains visited in priv...
13      hang when displaying unsorted bookmarks with k...
14      moving place  bookmark for bookmarks menu caus...
15      firefox hangs trying to open broken site for t...
16              specific pdf page takes to render  % cpu 
17      firefo

In [12]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\aneesa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [13]:
from nltk.corpus import stopwords

In [14]:
stop_words = set(stopwords.words('english')) 

In [15]:
processed = processed.apply(lambda x: ' ' .join(term for term in x.split() if term not in stop_words))

In [16]:
print(processed)

0       authentication required hangs firefox cpu othe...
1       print preview buttons readable windows black f...
2       page causes firefox completely hang several mi...
3       hang encoded character userinfo https domain c...
4       crash java lang illegalargumentexception org m...
5       one search nd line buttons visible search bar ...
6       statusbar text visible firefox android android...
7               open new tab button visible browser focus
8       intersection full height tab separators toolba...
9       browser window ui entirely visible resized min...
10      placeholder text color differs address bar sea...
11      error click pocket button security error conte...
12      networking shows domains visited private brows...
13        hang displaying unsorted bookmarks k+ bookmarks
14      moving place bookmark bookmarks menu causes ha...
15      firefox hangs trying open broken site tile dis...
16                   specific pdf page takes render % cpu
17      firefo

In [17]:
#from nltk.stem.snowball import SnowballStemmer

In [18]:
#stemmer = SnowballStemmer("english")

In [19]:
#processed = processed.apply(lambda x: ' ' .join(stemmer.stem(term) for term in x.split()))

In [20]:
#print(processed)

In [25]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\aneesa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [26]:
from nltk.stem import WordNetLemmatizer 

In [27]:
lemmatizer = WordNetLemmatizer() 

In [28]:
processed = processed.apply(lambda x: ' ' .join(lemmatizer.lemmatize(term) for term in x.split()))

In [29]:
processed

0       authentication required hang firefox cpu other...
1       print preview button readable window black fon...
2       page cause firefox completely hang several min...
3       hang encoded character userinfo http domain co...
4       crash java lang illegalargumentexception org m...
5       one search nd line button visible search bar s...
6       statusbar text visible firefox android android...
7               open new tab button visible browser focus
8       intersection full height tab separator toolbar...
9       browser window ui entirely visible resized min...
10      placeholder text color differs address bar sea...
11      error click pocket button security error conte...
12      networking show domain visited private browsin...
13          hang displaying unsorted bookmark k+ bookmark
14      moving place bookmark bookmark menu cause hang...
15      firefox hang trying open broken site tile display
16                    specific pdf page take render % cpu
17      firefo

In [32]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\aneesa\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [33]:
from nltk.tokenize import word_tokenize

In [34]:
allwords = []
for message in processed:
    words = word_tokenize(message)
    for w in words:
        allwords.append(w)
        
allwords = nltk.FreqDist(allwords)

print('Number of words: {}'.format(len(allwords)))
print('most common words: {}'.format(allwords.most_common(50)))

Number of words: 3720
most common words: [('test', 379), ('eclipse', 164), ('error', 141), ('intermittent', 135), ('failure', 121), ('org', 119), ('build', 113), ('>', 101), ('java', 99), ('memory', 98), ('j', 93), ('crash', 85), ('firefox', 84), ('theme', 79), ('plugin', 79), ('cpu', 77), ('dark', 72), ('button', 69), ('color', 68), ('timed', 68), ('http', 67), ('tab', 67), ('ui', 67), ('leak', 67), ('type', 67), ('exception', 64), ('page', 63), ('use', 62), ('window', 61), ('high', 59), ('code', 59), ('update', 59), ('file', 57), ('using', 56), ('<', 56), ('new', 55), ('nullpointerexception', 53), ('fails', 53), ('browser', 52), ('content', 51), ('internal', 51), ('assertion', 50), ('project', 50), ('method', 50), ('server', 49), ('usage', 49), ('freeze', 48), ('dom', 47), ('application', 47), ('text', 46)]


In [35]:
processed[0]

'authentication required hang firefox cpu otherwise busy throttled'

In [36]:
word_features = allwords.most_common(50)
word_features = [i[0] for i in word_features]
print(word_features)

['test', 'eclipse', 'error', 'intermittent', 'failure', 'org', 'build', '>', 'java', 'memory', 'j', 'crash', 'firefox', 'theme', 'plugin', 'cpu', 'dark', 'button', 'color', 'timed', 'http', 'tab', 'ui', 'leak', 'type', 'exception', 'page', 'use', 'window', 'high', 'code', 'update', 'file', 'using', '<', 'new', 'nullpointerexception', 'fails', 'browser', 'content', 'internal', 'assertion', 'project', 'method', 'server', 'usage', 'freeze', 'dom', 'application', 'text']


In [37]:
def find_features(message):
    words = word_tokenize(message)
    features = {}
    for word in word_features:
        features[word] = (word in words)
    return features

features = find_features(processed[0])

for key, value in features.items():
    if value == True:
        print(key)

firefox
cpu


In [38]:
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
vectorizer = TfidfVectorizer()

In [40]:
X = vectorizer.fit_transform(processed).toarray()

In [41]:
print(X.shape)

(2138, 3670)


In [42]:
pd.DataFrame(X, columns=vectorizer.get_feature_names()) 

__cfrunloopservicemachport  __format  __nscfdictionary  \
0                            0.0       0.0               0.0   
1                            0.0       0.0               0.0   
2                            0.0       0.0               0.0   
3                            0.0       0.0               0.0   
4                            0.0       0.0               0.0   
5                            0.0       0.0               0.0   
6                            0.0       0.0               0.0   
7                            0.0       0.0               0.0   
8                            0.0       0.0               0.0   
9                            0.0       0.0               0.0   
10                           0.0       0.0               0.0   
11                           0.0       0.0               0.0   
12                           0.0       0.0               0.0   
13                           0.0       0.0               0.0   
14                           0.0       0.0               0.0   
15                           0.0       0.0               0.0   
16                           0.0       0.0               0.0   
17                           0.0       0.0               0.0   
18                           0.0       0.0               0.0   
19                           0.0       0.0               0.0   
20                           0.0       0.0               0.0   
21                           0.0       0.0               0.0   
22                           0.0       0.0               0.0   
23                           0.0       0.0               0.0   
24                           0.0       0.0               0.0   
25                           0.0       0.0               0.0   
26                           0.0       0.0               0.0   
27                           0.0       0.0               0.0   
28                           0.0       0.0               0.0   
29                           0.0       0.0               0.0   
...                          ...       ...               ...   
2108                         0.0       0.0               0.0   
2109                         0.0       0.0               0.0   
2110                         0.0       0.0               0.0   
2111                         0.0       0.0               0.0   
2112                         0.0       0.0               0.0   
2113                         0.0       0.0               0.0   
2114                         0.0       0.0               0.0   
2115                         0.0       0.0               0.0   
2116                         0.0       0.0               0.0   
2117                         0.0       0.0               0.0   
2118                         0.0       0.0               0.0   
2119                         0.0       0.0               0.0   
2120                         0.0       0.0               0.0   
2121                         0.0       0.0               0.0   
2122                         0.0       0.0               0.0   
2123                         0.0       0.0               0.0   
2124                         0.0       0.0               0.0   
2125                         0.0       0.0               0.0   
2126                         0.0       0.0               0.0   
2127                         0.0       0.0               0.0   
2128                         0.0       0.0               0.0   
2129                         0.0       0.0               0.0   
2130                         0.0       0.0               0.0   
2131                         0.0       0.0               0.0   
2132                         0.0       0.0               0.0   
2133                         0.0       0.0               0.0   
2134                         0.0       0.0               0.0   
2135                         0.0       0.0               0.0   
2136                         0.0       0.0               0.0   
2137                         0.0       0.0               0.0   

      _cairo_array_allocate  _psutil_

In [43]:
Y = df['Priority']

In [44]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [45]:
print(Y.value_counts())

P3    925
P2    539
P1    294
P5    225
P4    155
Name: Priority, dtype: int64


In [46]:
from sklearn.ensemble import RandomForestClassifier
text_classifier = RandomForestClassifier(n_estimators=100, random_state=0)  
text_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [47]:
predictions = text_classifier.predict(X_test)

In [48]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  
print(accuracy_score(y_test, predictions))

[[ 26  10  27   0   0]
 [  2  56  42   1   0]
 [  3  20 148   2   3]
 [  0   1   3  29   0]
 [  0   2  18   2  33]]
              precision    recall  f1-score   support

          P1       0.84      0.41      0.55        63
          P2       0.63      0.55      0.59       101
          P3       0.62      0.84      0.71       176
          P4       0.85      0.88      0.87        33
          P5       0.92      0.60      0.73        55

    accuracy                           0.68       428
   macro avg       0.77      0.66      0.69       428
weighted avg       0.71      0.68      0.67       428

0.6822429906542056


In [49]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)

In [50]:
print(confusion_matrix(y_test,y_pred))  
print(classification_report(y_test,y_pred))  
print(accuracy_score(y_test, y_pred))

[[33 20  6  2  2]
 [12 63 22  3  1]
 [13 48 89 15 11]
 [ 0  0  5 28  0]
 [ 0 11 12  0 32]]
              precision    recall  f1-score   support

          P1       0.57      0.52      0.55        63
          P2       0.44      0.62      0.52       101
          P3       0.66      0.51      0.57       176
          P4       0.58      0.85      0.69        33
          P5       0.70      0.58      0.63        55

    accuracy                           0.57       428
   macro avg       0.59      0.62      0.59       428
weighted avg       0.60      0.57      0.57       428

0.572429906542056


In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
logreg = LogisticRegression(solver='liblinear', random_state=0)
#fit the model
logreg.fit(X_train, y_train)
y_pred_test = logreg.predict(X_test)

In [52]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,y_pred_test))  
print(classification_report(y_test,y_pred_test))  
print(accuracy_score(y_test, y_pred_test))

[[ 15   9  39   0   0]
 [  2  50  49   0   0]
 [  4  10 160   2   0]
 [  0   2  29   2   0]
 [  2   1  42   0  10]]
              precision    recall  f1-score   support

          P1       0.65      0.24      0.35        63
          P2       0.69      0.50      0.58       101
          P3       0.50      0.91      0.65       176
          P4       0.50      0.06      0.11        33
          P5       1.00      0.18      0.31        55

    accuracy                           0.55       428
   macro avg       0.67      0.38      0.40       428
weighted avg       0.63      0.55      0.50       428

0.5537383177570093


In [53]:
from sklearn.tree import DecisionTreeClassifier 
dtree_model = DecisionTreeClassifier(criterion = 'entropy').fit(X_train, y_train) 
dtree_predictions = dtree_model.predict(X_test) 
print("Accuracy:",metrics.accuracy_score(y_test, dtree_predictions))

Accuracy: 0.6822429906542056


In [54]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test,dtree_predictions))  
print(classification_report(y_test,dtree_predictions))  
print(accuracy_score(y_test, dtree_predictions))

[[ 31  12  19   1   0]
 [  6  62  28   2   3]
 [  6  24 131   4  11]
 [  0   1   2  30   0]
 [  0   2  13   2  38]]
              precision    recall  f1-score   support

          P1       0.72      0.49      0.58        63
          P2       0.61      0.61      0.61       101
          P3       0.68      0.74      0.71       176
          P4       0.77      0.91      0.83        33
          P5       0.73      0.69      0.71        55

    accuracy                           0.68       428
   macro avg       0.70      0.69      0.69       428
weighted avg       0.68      0.68      0.68       428

0.6822429906542056
